# Generated by Django 4.2.15 on 2024-09-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projetcs',
            new_name='Project',
        ),
    ]
